[project]
name = "uncute-rina-python"
version = "2.5.0"
requires-python = ">=3.14"
dependencies = [
    "ruff>=0.16.3",
    "discord.py>=2.7.1",
    #    "git+https://github.com/Rapptz/discord.py/",
    "motor>=3.7.1",
    "pymongo>=4.17.0",
    "pandas>=3.0.5",
    "apscheduler>=3.11.3",
    "matplotlib>=3.11.1",
    "aiohttp>=3.14.3",
    #     "flake8>=7.3.0",
    #     "flake8-pyproject>=1.2.4",
    #     "ruff>=0.16.2",
    #     "mypy>=2.3.0",
    #     "coverage>=7.15.4",
    "pip==26.2.1",
]

[project.optional-dependencies]
ci = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "ruff>=0.16.2",
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "typing-extensions>=4.16.0",
]

dev = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "ruff>=0.16.2",
    "mypy>=2.3.0",
    "coverage>=7.15.4",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]


[tool.mypy]
disable_error_code=["import-untyped", "no-redef"]
implicit_optional=true
allow_redefinition_new=true
local_partial_types=true
allow_redefinition=true

[[tool.mypy.overrides]]
module = "extensions.termdictionary.dictionaries.custom_dictionary"
ignore_errors = true

[tool.flake8]
max-line-length=119
exclude=[
    ".git",
    "venv",
    ".venv",
    "rina_docs",
]

[tool.coverage.run]
omit=[
    "*/unit_tests/*",
    "*/__init__.py",
    "*/module.py",
]


[tool.pytest.ini_options]
pythonpath="."
filterwarnings=["ignore::DeprecationWarning:discord.player"]
# Only necessary in python 3.12. discord.py imports `audioop-lts` in python 3.13 resolving this DeprecationWarning.

[tool.ruff]
exclude = [".venv", "unit_tests"]
line-length=119
target-version="py314"

[tool.ruff.lint]
select = [
    "ANN", # Type annotations would take wayyy too long to do properly  # HA YOU THOUGHT (I only spent 2 hours TwT)
    "ASYNC", # Async bugs
    "S", # Security bugs
    "A", # Built-in shadowing bugs
    "C4", # Generator expression lints / list comprehensions
    "EXE", # Checks that executable files are set up properly
    "FIX", # Grabs TODOs
    "ICN", # Catches weird imports
    "LOG", # Catches logging issues
    "SLF", # Catches reading private members
    # Catches redundant code
    #"SIM101", "SIM102", "SIM103", "SIM110", "SIM113", "SIM114", "SIM116", "SIM117", "SIM118", "SIM2", "SIM401", "SIM9",
    "TID", # More weird imports
    "PTH", # Pathlib
    "NPY", # NumPy
    "PD", # Pandas
    "PERF", # Performance lints. Speeeeeed ... in python?... Uhkay sure.
    "E", "W", # Standard warnings and errors
    "F", # Generic non-style mistakes
    "PLE", # Pylint errors
    "PLW", # Pylint warnings

    # Ruff-specific

    "RUF",
    "asyncio-dangling-task", # asyncio tasks can be GC'd and killed
    "implicit-optional", # Explicit Optional
    "unnecessary-iterable-allocation-for-first-element", # Turning something into a list to get the first element is slow
    "invalid-index-type", # Invalid index type
    "quadratic-list-summation", # Bizarre list merge

    # Assert issues
    "assignment-in-assert",
    "assert-with-print-message",
    "invalid-assert-message-literal-argument",

    "unnecessary-key-check", # Bizarre dict element access
    "parenthesize-chained-operators", # and/or bracketing
    "mutable-fromkeys-value", # Bad dict construction
    "default-factory-kwarg", # Defaultdict misuse
    "missing-f-string-syntax", # Something looks like an f-string, but is missing the `f`
    "invalid-formatter-suppression-comment", # Invalid supression comments
    "pytest-raises-ambiguous-pattern", # pytest issues
    "too-few-spaces-before-inline-comment",
    "implicit-optional", # Optional types should be properly marked
    "unused-unpacked-variable", # Unused variables
    "line-too-long", # Don't allow long lines: 79 chars max.
    "self-assigning-variable", # Allow self-assingment to indicate type
    "duplicate-isinstance-call", # Merge isinstance() calls by using tuples

    # Weird tests for characters that look similar
    "ambiguous-unicode-character-string",
    "ambiguous-unicode-character-comment",
    "blanket-noqa", # Blanket disabling lints isn't great
    "PTH", # pathlib still technically works
    "unsorted-dunder-all", "unsorted-dunder-slots", "unsorted-imports", # Sorted inputs are nice, but not *needed*  # "\_('-')_/" i did it anyway :)
    "redefined-loop-name", # Allow reassigning in loops
    "assert", # We should not use asserts (throw exceptions instead!), as optimized environments disable them

    "multiple-starts-ends-with",
    "needless-bool",
    "explicit-f-string-type-conversion",
    "if-stmt-min-max",
    "dict-index-missing-items",
    "collapsible-if",
    "unsorted-imports",
    "unnecessary-generator-set",
    "pytest-duplicate-parametrize-test-cases",
    "function-call-in-default-argument",
    "dict-index-missing-items",
    "slice-to-remove-prefix-or-suffix",
#    "non-unique-enums",
#    "blind-except",
    "invalid-module-name",
    "unintentional-type-annotation",
    "unnecessary-placeholder",
    "datetime-min-max",
    "runtime-import-in-type-checking-block",
]

ignore = [
    "unused-noqa", # different linters have different noqa triggers so aren't always 'unused'.
    "shebang-missing-executable-file",
    # Things we should probably do

    # Style stuff that's bad, but won't cause issues

    # Ignoring these more permanently
    "suspicious-non-cryptographic-random-usage", # We don't need a CSPRNG anywhere, right?
#    "suppressible-exception", "if-else-block-instead-of-if-exp", "yoda-conditions", # No suppressing exceptions. Use ternary operator; don't use yoda conditions.
    "global-statement", # We seem to be choosing to use globals
    "line-contains-todo", # Too much TODO
#    "collection-literal-concatenation", # [*a, *b] is apparently faster than a + b, but it's not *that* important
    "explicit-f-string-type-conversion", # Explicit f-string conversion is fine and readable
]
